# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  displayName: Install dependencies
  inputs:
    targetType: 'inline'
    script: |
      # Create directory for install dependencies
      ls
      cd '$(Build.ArtifactStagingDirectory)'
      mkdir SSIS
      # download and install SSIS build and deploy package
      cd SSIS
      Invoke-WebRequest -Uri "http://aka.ms/SSISDevOpsTools" -OutFile SSIS.exe
       Write-Host "Download complete"
      #install download package
      .\SSIS.exe /Q /C /T:D:\a\1\a\SSIS\SSIS
      ls
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      cd D:\a\1\a\SSIS\SSIS
      ls
- task: SSISBuild@1
  inputs:
    projectPath: './Integration Services Project5/'
    stripSensitive: false
    outputPath: '$(Build.ArtifactStagingDirectory)/SSISDMFT'
- task: SSISDeploy@1
  inputs:
    sourcePath: '$(Build.ArtifactStagingDirectory)\SSISDMFT\Integration Services Project5.ispac'
    destinationType: 'ssisdb'
    destinationServer: 'localhost\MSSQLSERVER01'
    destinationPath: '/SSISDB/Cix'
    authType: 'win'
    whetherOverwrite: 'yes'
    whetherContinue: 'no'
