# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      ls

- task: SSISBuild@1
  inputs:
    projectPath: './Integration Services Project5/'
    stripSensitive: false
    outputPath: '$(Build.ArtifactStagingDirectory)'
- task: SSISDeploy@1
  inputs:
    sourcePath: '$(Build.ArtifactStagingDirectory)/Development\Integration Services Project5.ispac'
    destinationType: 'ssisdb'
    destinationServer: 'localhost\MSSQLSERVER01'
    destinationPath: '/SSISDB/Cix'
    authType: 'win'
    whetherOverwrite: 'yes'
    whetherContinue: 'no'
